In [1]:
import numpy as np
import torch

In [12]:
a = np.random.rand(3,3)
a

array([[0.10370627, 0.13853338, 0.87380063],
       [0.60474879, 0.80955602, 0.40775596],
       [0.12880862, 0.11734802, 0.04835474]])

In [13]:
n=3
i=1
b = a[i, np.concatenate((np.r_[0:i], np.r_[i+1:n]))] # r_: rowwise merging
b

array([0.60474879, 0.40775596])

In [14]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[9, 5], [6, 8]])
c = a-b
c1 = c@c.T
print(c1)

[[73 36]
 [36 25]]


In [15]:
d = a@a.T - 2*a@b.T + b.T@b
print(d)

[[84 60]
 [10 14]]


In [20]:
d = a@a.T - a@b.T - b@a.T + b@b.T
print(d)

[[73 36]
 [36 25]]
